// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVf8-gAm9r7n1rzebjNGGGveWopyszTG8',
    appId: '1:870948591341:web:ebb99ecb1b512a7d369ee4',
    messagingSenderId: '870948591341',
    projectId: 'pontealdia-91ccd',
    authDomain: 'pontealdia-91ccd.firebaseapp.com',
    storageBucket: 'pontealdia-91ccd.appspot.com',
    measurementId: 'G-QRWRBKXW1C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc2v0YxUHBWwVOTx0GMxadCCg7iuV7JGI',
    appId: '1:870948591341:android:cf1f88c925d16dd8369ee4',
    messagingSenderId: '870948591341',
    projectId: 'pontealdia-91ccd',
    storageBucket: 'pontealdia-91ccd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbThvq9vPCtf8P2v4RHsD1al-sHhWdbKE',
    appId: '1:870948591341:ios:9dd03d654bb5860a369ee4',
    messagingSenderId: '870948591341',
    projectId: 'pontealdia-91ccd',
    storageBucket: 'pontealdia-91ccd.appspot.com',
    iosBundleId: 'com.example.ponteAlDia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbThvq9vPCtf8P2v4RHsD1al-sHhWdbKE',
    appId: '1:870948591341:ios:6cf16b4f6d086f11369ee4',
    messagingSenderId: '870948591341',
    projectId: 'pontealdia-91ccd',
    storageBucket: 'pontealdia-91ccd.appspot.com',
    iosBundleId: 'com.example.ponteAlDia.RunnerTests',
  );
}
